### ISSUE TITLE
Counter occasionally displays incorrect value...

### ISSUE THREAD

**Issue by julianthompson** [pqina/flip#50] opened 2022-10-06 19:54 UTC
Not sure if I'm doing something wrong, but sometimes the counter displays the incorrect value. (I'm essentially using the slow reveal code from https://pqina.nl/flip/ (slow reveal).

Here is my code:  

https://codepen.io/julianthompson/pen/poVOwdW

You'll need to refresh a few times to get the wrong value. Its usually one digit out. I got two wrong values in 10 refreshes. Counter 1 should be 631 and it displayed 231.

**Comment by rikschennink** [comment] 2022-10-12 07:15
Hi @julianthompson I tried to test this but couldn't see it happen. I'll leave this open for someone else to maybe help out.

**Comment by julianthompson** [comment] 2022-10-14 15:29
It's like 1 in 10 / 20 refreshes on chrome (os x) for me.

**Comment by ryno1234** [comment] 2022-12-16 20:17
I'm occasionally seeing incorrect values as well. This should say 

![image0 (7)](https://user-images.githubusercontent.com/92051/208182033-18165da0-0931-4aea-b165-31ed4c53ede8.jpeg)

If I refresh I can get updated / correct information. This is infrequent, but frequently enough to where we hear complaints about it.
<img width="280" alt="image" src="https://user-images.githubusercontent.com/92051/208182154-4ca4640a-9ab8-4273-aa16-d5952ed2fc57.png">

**Comment by rikschennink** [comment] 2022-12-17 13:53
I'm all ears to fix this but without any additional data or insight into why this might happen sometimes I can't reserve the time to look into this now.

**Comment by ryno1234** [comment] 2022-12-17 14:18
@rikschennink, understood. I'll take a look next time it occurs and see if I can trace the issue back.

**Comment by ryno1234** [comment] 2023-07-14 03:07
@rikschennink, I looked into this a little more. The counter is counting down using an epoch time despite sending `Tick.count.down` a different number of seconds.

Additionally the tick is happening incredibly rapidly, the numbers are just flying by.

**This is where it gets interesting:**
I cannot reproduce this issue by refreshing the page many times. No matter how many times I attempt to refresh (I tried about 30 times), the countdown works as expected. HOWEVER, If I open a new browser tab and type in the URL, let the autocomplete do its thing and show the site as a suggested site and then click on it, most of the time I will get the clock counting the time since epoch.

I further noticed that if I have my dev tools open and have "Disable Cache" enabled, the page seems to pull up correctly each time.

I know browsers like Chrome do a pre-fetch of sites when typing them into the browser. I'm wondering if that has anything to do with this. I'm not sure why, or how, but its very interesting.

**Comment by ryno1234** [comment] 2023-07-14 15:10
@rikschennink  I have the fix to this, but not sure the best way to commit it. I created a fork but see multiple variations of the source code in the `tick` folder. It seems the source code is duplicated in each of these variants.

How do you prefer your pull requests? I'd like to get this merged and rebuilt / deployed ASAP so I can put this in my rearview mirror.

Thanks for all your hard work on this library!

**Comment by ryno1234** [comment] 2023-07-19 13:27
> What did you change to make it work?

I moved where the determination of `tickExpectedTime` is performed in the `start()` function. We need to determine the `tickExpectedTime` value before we have the opportunity to sleep or hide the timer due to page visibility changes.

I submitted a pull request for the change. I did not create a new dist, however (required old Python and VS 2017)

**Comment by rikschennink** [comment] 2023-07-20 09:04
Thanks! I'll explore the fix next week, currently packing for a trip.

**Comment by ryno1234** [comment] 2023-07-20 21:16
> Thanks! I'll explore the fix next week, currently packing for a trip.

Enjoy!

**Comment by ryno1234** [comment] 2023-08-05 00:30
@rikschennink, just checking in on this. I'd prefer to use an official build vs. a build I do myself. Any plan on merging this soon? Hope the trip went well.

**Closed** 2023-08-08 13:57 UTC

**Comment by rikschennink** [comment] 2023-08-08 14:02
@ryno1234 sorry for the delay, just merged and published new release.

**Comment by ryno1234** [comment] 2023-08-30 19:57
@rikschennink, I realized this change was submitted in tick, but it hasn't been used to create a new version of the flip library. Is this something you can do? Or, instruct me how and I can do it and check it in and submit a PR.

Thank you!

**Comment by rikschennink** [comment] 2023-08-31 14:21
Ah okay, I'll see if I can merge.

**Comment by rikschennink** [comment] 2023-08-31 16:16
Just pushed 1.8.1
